# Generated by Django 5.2.12 on 2026-03-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
