# Generated by Django 5.2.12 on 2026-03-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_accomplishmentreport_accomplishmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishmentimage',
            name='image_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accomplishmentimage',
            name='image_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='accomplishmentimage',
            name='image_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accomplishmentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accomplishments/'),
        ),
    ]
