# Generated by Django 5.2.12 on 2026-03-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_accomplishmentimage_image_blob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total_hours', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Processed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
