# Generated by Django 5.2.12 on 2026-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='am_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='am_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pm_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pm_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
