# Generated by Django 5.2.12 on 2026-03-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_historyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyrecord',
            old_name='total_hours',
            new_name='hours',
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='am_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='am_out',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='pm_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='pm_out',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='time_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='time_out',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='status',
            field=models.CharField(default='Completed', max_length=50),
        ),
    ]
