# Generated by Django 5.2.12 on 2026-03-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_am_in_attendance_am_out_attendance_pm_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='time_in',
            new_name='am_time_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='time_out',
            new_name='am_time_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='am_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='am_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='pm_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='pm_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='pm_time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pm_time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
