# Generated by Django 5.2.12 on 2026-03-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_rename_total_hours_historyrecord_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
