# Generated by Django 5.2.12 on 2026-03-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_intern_session_token_intern_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
