# Generated by Django 5.2.12 on 2026-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_intern_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='profile_picture_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='profile_picture_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
