# Generated by Django 5.2.12 on 2026-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='is_typing_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
