# Generated by Django 5.2.12 on 2026-03-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_intern_is_typing_to_intern_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
