# Generated by Django 5.2.12 on 2026-03-29 00:59

from django.db import migrations


def sync_hours(apps, schema_editor):
    Intern = apps.get_model('attendance', 'Intern')
    Attendance = apps.get_model('attendance', 'Attendance')
    
    from django.utils import timezone
    from datetime import datetime, time
    
    def get_effective_hours(start_dt, end_dt):
        if not start_dt or not end_dt: return 0
        local_start = timezone.localtime(start_dt)
        local_end = timezone.localtime(end_dt)
        sec = (local_end - local_start).total_seconds()
        if sec <= 0: return 0
        lunch_start = timezone.make_aware(datetime.combine(local_start.date(), time(12, 0)))
        lunch_end = timezone.make_aware(datetime.combine(local_start.date(), time(13, 0)))
        overlap_start = max(local_start, lunch_start)
        overlap_end = min(local_end, lunch_end)
        if overlap_start < overlap_end:
            sec -= (overlap_end - overlap_start).total_seconds()
        return sec / 3600

    for intern in Intern.objects.filter(is_staff=False):
        records = Attendance.objects.filter(student_id=intern.student_id)
        total = sum(get_effective_hours(r.am_time_in, r.am_time_out) + get_effective_hours(r.pm_time_in, r.pm_time_out) for r in records)
        intern.total_hours = total
        intern.save()

class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_intern_total_hours'),
    ]

    operations = [
        migrations.RunPython(sync_hours),
    ]
