# Generated by Django 5.2.12 on 2026-03-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20260329_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='is_typing_to',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='last_active',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_id',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_id',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student_id', 'date'], name='attendance__student_76a8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student_id'], name='attendance__student_018d17_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance__date_61f2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender_id', 'receiver_id'], name='attendance__sender__ec11cc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver_id', 'is_read'], name='attendance__receive_a7185c_idx'),
        ),
    ]
