# Generated by Django 5.2.12 on 2026-04-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
